-- Generated by generate_ofarm_ed25519_vectors.py; do not edit.
-- Corpus SHA-256: sha256:55c1a95e60a6bcaccc9222fbd2b67d384767ca92faa1e9c049789c38eefc60e1

DO $ofarm_canonical_vectors$
DECLARE
    vector record;
    observed boolean;
    altered bytea;
    byte_index integer;
    bit_index integer;
    public_key bytea := decode('d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a', 'hex');
    signed_bytes bytea := decode('004f4641524d322d54454e414e542d4341504142494c4954592d4b4d532d505245464c494748542d563100', 'hex');
    signature bytea := decode('b8c5d75bfcdfaf6c33ae31eb6dba6f47ae6a7c11d925982ffbc00d2897a15c1bdee4b25b894d6a64f22466d698d536bc5a87fa0650ead4da5cc6496154ffe102', 'hex');
BEGIN
    FOR vector IN
        SELECT *
        FROM (VALUES
        ('rfc8032-empty-positive', decode('d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a', 'hex'), decode('', 'hex'), decode('e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b', 'hex'), true),
        ('kms-preflight-positive', decode('d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a', 'hex'), decode('004f4641524d322d54454e414e542d4341504142494c4954592d4b4d532d505245464c494748542d563100', 'hex'), decode('b8c5d75bfcdfaf6c33ae31eb6dba6f47ae6a7c11d925982ffbc00d2897a15c1bdee4b25b894d6a64f22466d698d536bc5a87fa0650ead4da5cc6496154ffe102', 'hex'), true),
        ('negative-zero-public-key', decode('0100000000000000000000000000000000000000000000000000000000000080', 'hex'), decode('', 'hex'), decode('e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b', 'hex'), false),
        ('negative-zero-r', decode('d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a', 'hex'), decode('', 'hex'), decode('01000000000000000000000000000000000000000000000000000000000000805fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b', 'hex'), false),
        ('identity-r-valid-equation', decode('d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a', 'hex'), decode('', 'hex'), decode('0100000000000000000000000000000000000000000000000000000000000000756cf9b1d6f0d7a979b9d2af3dc2bc1294ec7cb6daa20eaff534c024fc57920f', 'hex'), false),
        ('zero-public-key', decode('0000000000000000000000000000000000000000000000000000000000000000', 'hex'), decode('', 'hex'), decode('e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b', 'hex'), false),
        ('zero-r', decode('d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a', 'hex'), decode('', 'hex'), decode('00000000000000000000000000000000000000000000000000000000000000005fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b', 'hex'), false),
        ('identity-public-key', decode('0100000000000000000000000000000000000000000000000000000000000000', 'hex'), decode('', 'hex'), decode('e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b', 'hex'), false),
        ('small-order-two-public-key', decode('0200000000000000000000000000000000000000000000000000000000000000', 'hex'), decode('', 'hex'), decode('e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b', 'hex'), false),
        ('non-main-subgroup-public-key', decode('9599999999999999999999999999999999999999999999999999999999999999', 'hex'), decode('', 'hex'), decode('e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b', 'hex'), false),
        ('noncanonical-f5-public-key', decode('f5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f', 'hex'), decode('', 'hex'), decode('e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b', 'hex'), false),
        ('noncanonical-f6-r', decode('d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a', 'hex'), decode('', 'hex'), decode('f6ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f5fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b', 'hex'), false),
        ('scalar-s-equals-l', decode('d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a', 'hex'), decode('', 'hex'), decode('e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e06522490155edd3f55c1a631258d69cf7a2def9de1400000000000000000000000000000010', 'hex'), false),
        ('scalar-s-greater-than-l', decode('d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a', 'hex'), decode('', 'hex'), decode('e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e06522490155eed3f55c1a631258d69cf7a2def9de1400000000000000000000000000000010', 'hex'), false),
        ('scalar-high-bit', decode('d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a', 'hex'), decode('', 'hex'), decode('e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a108b', 'hex'), false),
        ('all-zero-signature', decode('d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a', 'hex'), decode('', 'hex'), decode('00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', 'hex'), false)
        ) AS corpus(identifier, public_key, signed_bytes, signature, expected)
    LOOP
        observed := ofarm_crypto.ed25519_verify(
            vector.public_key, vector.signed_bytes, vector.signature
        );
        IF observed IS DISTINCT FROM vector.expected THEN
            RAISE EXCEPTION 'canonical Ed25519 vector % disagreed',
                vector.identifier;
        END IF;
    END LOOP;

    FOR byte_index IN 0..octet_length(public_key) - 1 LOOP
        FOR bit_index IN 0..7 LOOP
            altered := set_byte(
                public_key,
                byte_index,
                get_byte(public_key, byte_index) # (1 << bit_index)
            );
            IF ofarm_crypto.ed25519_verify(
                altered, signed_bytes, signature
            ) IS DISTINCT FROM false THEN
                RAISE EXCEPTION 'canonical public-key bit flip accepted';
            END IF;
        END LOOP;
    END LOOP;
    FOR byte_index IN 0..octet_length(signed_bytes) - 1 LOOP
        FOR bit_index IN 0..7 LOOP
            altered := set_byte(
                signed_bytes,
                byte_index,
                get_byte(signed_bytes, byte_index) # (1 << bit_index)
            );
            IF ofarm_crypto.ed25519_verify(
                public_key, altered, signature
            ) IS DISTINCT FROM false THEN
                RAISE EXCEPTION 'canonical signed-bytes bit flip accepted';
            END IF;
        END LOOP;
    END LOOP;
    FOR byte_index IN 0..octet_length(signature) - 1 LOOP
        FOR bit_index IN 0..7 LOOP
            altered := set_byte(
                signature,
                byte_index,
                get_byte(signature, byte_index) # (1 << bit_index)
            );
            IF ofarm_crypto.ed25519_verify(
                public_key, signed_bytes, altered
            ) IS DISTINCT FROM false THEN
                RAISE EXCEPTION 'canonical signature bit flip accepted';
            END IF;
        END LOOP;
    END LOOP;

    IF ofarm_crypto.ed25519_verify(
        substring(public_key FROM 1 FOR 31), signed_bytes, signature
    ) IS DISTINCT FROM false
        OR ofarm_crypto.ed25519_verify(
            public_key || decode('00', 'hex'), signed_bytes, signature
        ) IS DISTINCT FROM false
        OR ofarm_crypto.ed25519_verify(
            public_key, signed_bytes, substring(signature FROM 1 FOR 63)
        ) IS DISTINCT FROM false
        OR ofarm_crypto.ed25519_verify(
            public_key, signed_bytes, signature || decode('00', 'hex')
        ) IS DISTINCT FROM false
        OR ofarm_crypto.ed25519_verify(
            public_key, decode(repeat('00', 8193), 'hex'), signature
        ) IS DISTINCT FROM false
        OR ofarm_crypto.ed25519_verify(
            public_key, decode(repeat('00', 8192), 'hex'), signature
        ) IS DISTINCT FROM false THEN
        RAISE EXCEPTION 'canonical direct length boundary was not refused';
    END IF;
END
$ofarm_canonical_vectors$;

DO $ofarm_canonical_boundary_fuzz$
DECLARE
    public_key_lengths integer[] := ARRAY[0, 1, 30, 31, 32, 33, 34, 63, 64, 65, 95];
    signed_bytes_lengths integer[] := ARRAY[0, 1, 2, 31, 32, 63, 64, 127, 255, 1024, 8191, 8192, 8193, 8447, 16384];
    signature_lengths integer[] := ARRAY[0, 1, 31, 32, 62, 63, 64, 65, 66, 127, 159];
    state bigint := 1327217885;
    public_key_length integer;
    signed_bytes_length integer;
    signature_length integer;
    fill_octet text;
    iteration integer;
    observed boolean;
BEGIN
    FOR iteration IN 1..4096 LOOP
        state := (state * 48271) % 2147483647;
        public_key_length := public_key_lengths[
            1 + (state % array_length(public_key_lengths, 1))::integer
        ];
        state := (state * 48271) % 2147483647;
        signed_bytes_length := signed_bytes_lengths[
            1 + (state % array_length(signed_bytes_lengths, 1))::integer
        ];
        state := (state * 48271) % 2147483647;
        signature_length := signature_lengths[
            1 + (state % array_length(signature_lengths, 1))::integer
        ];
        state := (state * 48271) % 2147483647;
        fill_octet := lpad(to_hex((state % 256)::integer), 2, '0');

        observed := ofarm_crypto.ed25519_verify(
            decode(repeat(fill_octet, public_key_length), 'hex'),
            decode(repeat(fill_octet, signed_bytes_length), 'hex'),
            decode(repeat(fill_octet, signature_length), 'hex')
        );
        IF observed IS DISTINCT FROM false THEN
            RAISE EXCEPTION
                'canonical SQL boundary fuzz case % was not refused', iteration;
        END IF;
    END LOOP;
END
$ofarm_canonical_boundary_fuzz$;
