"""Exact PostgreSQL release accepted by the issue #174 database boundary."""

SUPPORTED_POSTGRESQL_SERVER_VERSION_NUM = 170010
SUPPORTED_POSTGRESQL_VERSION = "17.10"
SUPPORTED_POSTGRESQL_SERVER_VERSION = "17.10 (Debian 17.10-1.pgdg13+1)"


__all__ = (
    "SUPPORTED_POSTGRESQL_SERVER_VERSION_NUM",
    "SUPPORTED_POSTGRESQL_SERVER_VERSION",
    "SUPPORTED_POSTGRESQL_VERSION",
)
